import React, { ReactNode, createContext, useState, useContext } from 'react';
import Head from 'next/head';
import { Oswald, Source_Serif_Pro } from '@next/font/google';
import Drawer from '../drawer/Drawer';
import { drawerContext } from '@/utils/drawerContext';
import Select from '../select/Select';
import { themeContext } from '@/utils/themeContext';

const oswald = Oswald({ weight: '700', subsets: ['latin'] });
const ssp = Source_Serif_Pro({ weight: '400', subsets: ['latin'] });

export default function Layout({ children }: { children: ReactNode }) {
  const { dState, setDSTate } = useContext(drawerContext);
  const { themes, themeState, setThemeState } = useContext(themeContext);

  const themeStrings = (): string[] => {
    const arr = [];
    for (let theme in themes) {
      arr.push(themes[theme]);
    }
    return arr;
  };

  const drawerItems = [
    {
      title: 'test',
    },
  ];

  const drawerFooter = (
    <Select
      title="Themes"
      options={themeStrings()}
      valState={themeState}
      setValState={setThemeState}
    ></Select>
  );

  return (
    <>
      <Head>
        <title>Pokemon Raid Utility</title>
        <meta name="Next and Daisy UI" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Drawer drawerItems={drawerItems} footer={drawerFooter}>
        <div className="min-h-screen bg-neutral-content flex justify-between flex-col">
          <header className="h-16 bg-base-300 flex justify-between items-center px-4">
            <div
              className={`${oswald.className} font-bold primary-content flex-1`}
            >
              Pokemon Raid Utility
            </div>

            <button
              className={`${oswald.className} btn btn-primary font-bold`}
              onClick={() => setDSTate((prev: boolean) => !prev)}
            >
              Menu
            </button>
          </header>
          <main className="bg-blue-500">{children}</main>
          <footer className="bg-base-300 h-16 shadow-2xl shadow-secondary flex justify-center items-center"></footer>
        </div>
      </Drawer>
    </>
  );
}
