import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Card1 from '@/components/card/Card1';
import { DropDownMenu } from '@/components/dropDown/DropDown';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Daisy UI Practice</title>
        <meta name="Next and Daisy UI" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-neutral-content flex justify-between flex-col">
        <header className="h-12 bg-red-500">
          <div>f</div>
        </header>
        <main className="bg-blue-500">
          <div>f</div>
        </main>
        <footer className="bg-green-500 h-12">f</footer>
      </div>
    </>
  );
}
